server:
  port: 8893
spring:
  application:
    name: user-consumer
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8500/eureka/
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true #开启hystrix熔断器
